consider minus when reading data
sejoonoh/GTA-Tensor pull request #1
Opened 2020-05-19 13:25 UTC by dawonahn

2020-05-19 15:31 UTC, sejoonoh commented on src/GTA.cpp
> +		    X.vale[i] = val;
X.value[i]=val;

2020-05-19 15:31 UTC, sejoonoh commented on src/GTA.cpp
> +            X.value[i] = 0 * val;
X.value[i]=-val;

2020-05-19 15:31 UTC, sejoonoh requested changes
Please review the comments

2020-05-20 01:30 UTC, dawonahn commented
> Please review the comments

Sorry for mistakes, I edited them again.

2020-05-20 15:10 UTC, sejoonoh approved these changes

2020-05-20 15:10 UTC, merged